DELETE FROM User;
DELETE FROM Book;
DELETE FROM Author;
DELETE FROM Role;
DELETE FROM Type;

CREATE TABLE IF NOT EXISTS Book (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    author_id INTEGER REFERENCES Author(id),
    type_id INTEGER REFERENCES Book(id)
);

CREATE TABLE IF NOT EXISTS Author (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS User(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role_id INTEGER REFERENCES Role(id),
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Type(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Role(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

INSERT INTO Role (name) VALUES ('ADMIN');
INSERT INTO Role (name) VALUES ('USER');
INSERT INTO Author (name) VALUES ('Camus');